### ISSUE TITLE
Add two new fields: sub/obj category

### ISSUE THREAD

**Issue by cmungall** [mapping-commons/SSSOM#13]
When mapping ontologies that contain many different kinds of entities (e.g NCIT) or even a few (GO) it can be useful to see the category of subject and object. This can be used to visually and computationally weed out false positives (e.g vector-sensu-math vs vector-sensu-infectius disease).

The source of categories may be domain-dependent. COB or biolink could be used for bio. It might still be useful to have a fixed level so that it is easy to compare like with like

**Comment by matentzn** [comment]
I made a PR (#15), but it may be difficult to communicate the purpose of these clearly; requiring CV terms will essentially create the necessity for lookup (I guess adding "subject_category_label" would be real overkill), so I probably prefer this to be simple label whose scope is the current mapping set..

**Comment by matentzn** [comment]
The element is now in SSSOM:

```
  subject_category:
    mixins:
      - subject_field
    description: The conceptual category to which the subject belongs to. This can
      be a string denoting the category or a term from a controlled vocabulary.
    range: string
```
