### ISSUE TITLE
Clarify the description of `mapping_provider`

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom#400]
I think the description needs to be updated here. These URIs don't actually point to resources, so what are you supposed to do with this? This is more of a comment string since I'm not sure there's a good way to actually capture this information unless it's supposed to point to a metadata file or the source data itself

_Originally posted by @cthoyt in https://github.com/mapping-commons/sssom/pull/394#discussion_r1827981496_

**Comment by nichtich** [comment]
Required by https://github.com/gbv/jskos/issues/108

**Comment by matentzn** [comment]
The current definition is:

```
mapping_provider:
    description: URL pointing to the source that provided the mapping, for example
      an ontology that already contains the mappings, or a database from which it was derived.
    range: uri
    instantiates: sssom:Propagatable
    annotations:
      propagated: true
    examples:
      - value: https://www.ohdsi.org/
        description: A URL pointing to the Observational Health Data Sciences and Informatics initiative.
      - value: https://monarchinitiative.org/
        description: A URL pointing to the Monarch Initiative Resource.
```

Assuming you are both after a glass clear rationale why URL vs URI/RDFS resource. 

I personally wanted to keep this as open as possible. What I originally _intended_ is of course using a resource id, like an infores CURIE (e.g. infores:go, ror:123), but for the groups I was working with it was too much of a barrier (like OHDSI) - they just simply would not fill in this field if I would ask for it to be a resources identifier.


I dont know what is best... Opinions?
