### ISSUE TITLE
Why is `see_also` typed as a string, rather than as a URI?

### ISSUE THREAD

**Issue by gouttegd** [mapping-commons/sssom#422]
The `see_also` slot is typed as a `xsd:string`, even though the definition explicitly states the slot is expected to contain a URL (or several URLs, as the slot is multi-valued):

```yaml
see_also:
  description: A URL specific for the mapping instance. E.g. for kboom we have a
    per-mapping image that shows surrounding axioms that drive probability. Could
    also be a github issue URL that discussed a complicated alignment
  slot_uri: rdfs:seeAlso
  examples:
    - value: https://github.com/mapping-commons/mh_mapping_initiative/pull/41
      description: A URL pointing to the pull request that introduced the mapping.
  range: string
  multivalued: true
```

Is there a reason for this typing? We have other slots that do have a `xsd:uri` type, so why not this one?
