### ISSUE TITLE
New metadata element: mapping_cardinality

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/SSSOM#53]
Proposal: add a new field `mapping_cardinality` which can take the following values:
1:n, 1:1, n:1, 1:0, 0:1

These are in principle derivable from the mapping set, but turn out to be super useful for querying and analysis to begin with.

given a mapping <s,p,o>
- `1:n`: s is mapped to more than o with relation p
- `1:1`: s is mapped to exactly 1 o with relation p
- `n:1`: more than 1 s is mapped to the same o with relation p
- `1:0`: o is "sssom:NoMatch"
- `0:1`: s is "sssom:NoMatch"

**Comment by matentzn** [comment]
From slack:

```
enums:
  status_enum:
    permissible_values:
      development: 
      release:
slots:
  status:
     range: status_enum
     required: false
```
